### ISSUE TITLE
pygame.error: Unrecognized audio format

### ISSUE THREAD

**Issue by Barry1915** [wszqkzqk/pypvz#4]
$ python main.py    
pygame 2.1.2 (SDL 2.0.16, Python 3.10.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/home/barry/Games/plant/pypvz/main.py", line 3, in <module>
    from source import tool
  File "/home/barry/Games/plant/pypvz/source/tool.py", line 216, in <module>
    pg.mixer.music.load(os.path.join(os.path.dirname(os.path.dirname(__file__)) ,"resources", "music", "intro.opus"))
pygame.error: Unrecognized audio format

**Comment by Barry1915** [comment]
操作系统：Manjaro Linux5.16

**Comment by Barry1915** [comment]
python：3.10

**Comment by Barry1915** [comment]
wait for replay

**Comment by wszqkzqk** [comment]
没有装opus的库吧

**Comment by wszqkzqk** [comment]
我音频用的opus编码，你这里没有编码器

**Comment by Barry1915** [comment]
我试试看怎么装opus

**Comment by wszqkzqk** [comment]
> 我试试看怎么装opus

pacman -S搜索一下

**Comment by Barry1915** [comment]
装过了
![image](https://user-images.githubusercontent.com/76513632/174945195-fe682bdf-8b1c-4a90-b675-5d137d9a70e6.png)

**Comment by wszqkzqk** [comment]
pygame版本是什么

**Comment by wszqkzqk** [comment]
我的manjaro没有问题

**Comment by Barry1915** [comment]
![image](https://user-images.githubusercontent.com/76513632/174945300-1934233a-f7fa-495c-9b56-8b90c997539b.png)

**Comment by wszqkzqk** [comment]
> ![image](https://user-images.githubusercontent.com/76513632/174945300-1934233a-f7fa-495c-9b56-8b90c997539b.png)

manjaro不需要pip安装，pacman有

**Comment by Barry1915** [comment]
sudo pacman -S python-pygame,我装了这个，仍然提示那个编码问题

**Comment by wszqkzqk** [comment]
我们环境是一样的，应该没有问题才对,pygame早就支持opus了

**Comment by Barry1915** [comment]
确实有点奇怪，慢点我再看看

**Comment by wszqkzqk** [comment]
opusfile安装了吗

**Comment by wszqkzqk** [comment]
没有反馈吗？
